import { PAL } from './config.js?v=0.25.0';

// Pixel art is written as text grids: each character is one pixel and maps
// to a palette colour ('.' is transparent). Each sprite is drawn once onto
// its own small canvas at start-up, plus a pale "hit flash" copy.
const KEY = {
  k: PAL.ink,
  b: PAL.blueDark,
  B: PAL.blue,
  p: PAL.bluePale,
  c: PAL.cream,
  l: PAL.amberLight,
  a: PAL.amber,
  A: PAL.amberSoft,
  o: PAL.amberDark,
  r: PAL.red,
  R: PAL.redDark,
  s: PAL.redSoft,
  g: PAL.grey,
  // Rust Moon: sand, tan and dark tan (canvas, planks, desert hide).
  d: '#c9ab86',
  e: '#9a7352',
  f: '#5e4434',
  h: '#a7a4ad', // steel (gun barrels)
  n: '#46444d', // dark gunmetal
  // Frostring: ice, from frost-white to deep blue.
  i: '#e6eef7',
  j: '#b8cde3',
  m: '#7f9cc0',
  q: '#4d6890',
  // Double-detail extras: the palest glass highlight and the deepest hull shade.
  P: '#c8d4ec',
  D: '#232b4a',
  x: '#5a1f22', // the darkest red (shaded flesh and hulls)
  y: '#f6dcae', // a pale hot glow
  G: '#8c8992', // light steel
};

const ART = {
  // The player's ship, facing right. Cream canopy, steel-blue hull, amber trim.
  player: [
    '....kkk...........',
    '...kpppk..........',
    '..kBppcpk.........',
    'kkkBBppppkkkkk....',
    'kAkBBpppppaalck...',
    'kaAkBBBppppppccck.',
    'kAkBBBBBBBBBbkkk..',
    'kkkbBBBBBbkkkk....',
    '..kbbBBbk.........',
    '...kbbbk..........',
    '....kkk...........',
  ],
  // Small dusty-red pod that drifts straight across.
  drifter: [
    '...kkkk...',
    '..kRrrRk..',
    '.kRrssrRkk',
    'kcRrrrrRRk',
    'kcRrrrrRRk',
    '.kRrssrRkk',
    '..kRrrRk..',
    '...kkkk...',
  ],
  // Living alien manta: raw red flesh, cream teeth, a little amber eye.
  weaver: [
    '.........kk',
    '.......kkrk',
    '....kkkrrRk',
    'kkkklsrrrRk',
    '.kccssrrrRk',
    'kkkklsrrrRk',
    '....kkkrrRk',
    '.......kkrk',
    '.........kk',
  ],
  // Armoured gunship with a twin cannon on its left side.
  gunner: [
    '....kkkkkk....',
    '...kgBBBBgk...',
    '..kgBpppBBgk..',
    'kkkkgBBBBBBgk.',
    'kggkRrrsrRBgkk',
    '.kkkRrsllrRBgk',
    'kggkRrrsrRBgkk',
    'kkkkgBBBBBBgk.',
    '..kgBBBBBBgk..',
    '...kgBBBBgk...',
    '....kkkkkk....',
  ],
  // Fast red dart that steers towards the player.
  seeker: [
    '......kkk.',
    '....kkRrk.',
    '..kkRrrRkk',
    'kclsrrrRRk',
    '..kkRrrRkk',
    '....kkRrk.',
    '......kkk.',
  ],
  // Slow, harmless cargo pod. Shoot it to release the pickup inside (the
  // slot in the middle shows the pickup's colour).
  carrier: [
    '..kkkkkkkkk..',
    '.kpppppppppk.',
    'kpBBBBBBBBBpk',
    'kBbkkkkkkkbBk',
    'kBbk.....kbBk',
    'kBbkkkkkkkbBk',
    'kpBBBBBBBBBpk',
    '.kbbbbbbbbbk.',
    '..kkkkkkkkk..',
  ],
  // Sniper: a long-barrelled gunship. Shows an aiming line, then fires a
  // fast shot along it.
  sniper: [
    '......kkkkkk..',
    '....kkBBBBppk.',
    'kkkkkBBrrBBBpk',
    'cclccbBrsBBBBk',
    'kkkkkBBrrBBBpk',
    '....kkbbbbbbk.',
    '......kkkkkk..',
  ],
  // Spinner: a rotating disc that sprays bullets in a star pattern.
  spinner: [
    '.....k.....',
    '....kgk....',
    '...kBBBk...',
    '.kkBpppBkk.',
    'kgBprrrpBgk',
    'kgBprsrpBgk',
    'kgBprrrpBgk',
    '.kkBpppBkk.',
    '...kBBBk...',
    '....kgk....',
    '.....k.....',
  ],
  // Rust Moon: a cliff turret, armoured shut...
  turretShut: [
    '....kkkk...',
    '..kkooook..',
    '.koAAAAook.',
    '.koAoooAok.',
    'kkkkkkkkkkk',
    'kgRgRgRgRgk',
    'kkkkkkkkkkk',
  ],
  // ...and open, showing its soft red core and barrel (only now can it be hurt).
  turretOpen: [
    '.....kkkk..',
    '....kooook.',
    'kkkkkrssrok',
    'cclckrlsrok',
    'kkkkkrssrok',
    'kgRgRgRgRgk',
    'kkkkkkkkkkk',
  ],
  // Rust Moon: a low, fast skimmer that hugs the canyon floor.
  skimmer: [
    '......kkkk..',
    '...kkkaAAak.',
    '.kkoooaaaaak',
    'klcoooooooRk',
    '.kkRRRRRRkk.',
    '...kkkkkk...',
  ],
  // Rust Moon: a six-legged mortar crawler; its stubby tube points up-left.
  crawler: [
    '..kk..........',
    '.kok..........',
    '..kok.........',
    '...kokkkkkk...',
    '...kRRRRRRRk..',
    '..kRrsrrrsrRk.',
    '..kRRRRRRRRRk.',
    '..k.k.k.k.k.k.',
    '.k.k.k...k.k.k',
  ],
  // Rust Moon: a raider, a small armed fighter (rust-red hull, swept-back
  // gunmetal wings, amber cockpit); its gun is in its nose, facing left.
  raider: [
    '.........kkk.',
    '.......kkggk.',
    '......kgggk..',
    '..kkkkRRrrRk.',
    'kclgRRsraaRRk',
    '..kkkkRRrrRk.',
    '......kgggk..',
    '.......kkggk.',
    '.........kkk.',
  ],
  // Siege Crawler's floating mine (its light blinks, see crawler.js).
  mine: [
    '...p...',
    '.p.k.p.',
    '..kBk..',
    'pkBsBkp',
    '..kBk..',
    '.p.k.p.',
    '...p...',
  ],
  // Siege Crawler's attack drone, gun at the front (left).
  drone: [
    '.kkkkk..',
    'kgAoooAk',
    'lcooooRk',
    'kgAoooAk',
    '.kkkkk..',
  ],
  // Tiny ship used for the lives counter.
  lifeIcon: [
    '.kkk...',
    'kABpkk.',
    'kaBppck',
    'kABpkk.',
    '.kkk...',
  ],
};

// Rust Moon's own versions of the enemy types it shares with level 1, chosen
// by the owner (v0.16.0) from four sets: the "Dust Pirates", desert raiders
// who patch their craft together from canvas, planks and rust-red metal.
// Each is exactly the size of its level 1 cousin and behaves exactly the
// same; only the look changes. (Cargo pods look the same on every level:
// their light is a signal.)
const RUST_ART = {
  // Pod -> sail skiff: a small patched hull under a canvas sail.
  drifter: [
    '.....kk...',
    '....kcck..',
    '...kcccck.',
    '..kkkekkkk',
    'kaRrrrrrRk',
    'klRssrrrRk',
    '.kRRRRRRk.',
    '..kkkkkk..',
  ],
  // Weaver -> dust bat: a native creature with ragged wings and a snapping
  // mouth (it still bleeds lightly, like the weaver).
  weaver: [
    '......k.k..',
    '.....kdkdk.',
    '....kddedk.',
    'kk.kdeeek..',
    'kcklseeefkk',
    'kk.kdeeek..',
    '....kddedk.',
    '.....kdkdk.',
    '......k.k..',
  ],
  // Gunship -> sand galleon: a flying ship with two sails, portholes, a plank
  // keel and twin cannons out front.
  gunner: [
    '......kk..kk..',
    '.....kcckkcck.',
    '....kccckcccck',
    '...kkkkkkkkkkk',
    'hhkRrrrrrrrrRk',
    'kkRrcRcRcRrrRk',
    'hhkRrrrrrrrrRk',
    '.kRRRRRRRRRRk.',
    '..kfefefefek..',
    '...kkkkkkkkk..',
    '..............',
  ],
  // Seeker -> kite glider: a fast canvas-winged glider.
  seeker: [
    '.....kk...',
    '...kkcck..',
    '.kkcccccrk',
    'kaRRRRRrrk',
    '.kkcccccrk',
    '...kkcck..',
    '.....kk...',
  ],
  // Sniper -> harpoon gun: a long barbed harpoon on a patched hull.
  sniper: [
    '..........kk..',
    '.........kcck.',
    'kk.....kkkcckk',
    'ckkhhhhhRrrrRk',
    'kk.....kRsrRek',
    '........kRRRk.',
    '.........kkk..',
  ],
  // Spinner -> windmill: four canvas sails (drawn spinning).
  spinner: [
    '....kcckk..',
    '.k..kccddk.',
    'kdk.kccdk..',
    'kddkkcdk...',
    'cccdfRfkkkk',
    'ccccRRRcccc',
    'kkkkfRfdccc',
    '...kdckkddk',
    '..kdcck.kdk',
    '.kddcck..k.',
    '..kkcck....',
  ],
};
// Frostring's own versions of the shared enemy types, chosen by the owner
// from eight sets: the "Ice Harvesters", the invaders' mining crews
// strip-mining the comet ring, in yellow-and-black hazard paint with drills
// and saw blades. Same sizes and behaviour as level 1 (cargo pods unchanged).
const FROST_ART = {
  // Pod -> drill pod: a hazard-striped pod with a drill for a nose.
  drifter: [
    '..kkkkkk..',
    '.kAaAaAak.',
    'kakAkAkAak',
    'hhkgggggak',
    'hhkgggggak',
    'kAkAkAkAak',
    '.kkkkkkkk.',
    '..........',
  ],
  // Weaver -> tunnel grub: a fat, ridged creature that bores through ice
  // (it still bleeds lightly, like the weaver).
  weaver: [
    '...........',
    '..kkkkkkk..',
    '.kcdcdcdck.',
    'kscdcdcdcek',
    'kccdcdcdcek',
    'kscdcdcdcek',
    '.kcdcdcdck.',
    '..kkkkkkk..',
    '...........',
  ],
  // Gunship -> ice cutter: a hauler with a saw blade out front and a cab.
  gunner: [
    '....kkkkkk....',
    '...kaaaaaak...',
    '..kaAkAkAak...',
    '.khkkkkkkkkk..',
    'hhhkgggggggak.',
    'hlhkgnnngggak.',
    'hhhkgggggggak.',
    '.khkkkkkkkkk..',
    '..kaAkAkAak...',
    '...kaaaaaak...',
    '....kkkkkk....',
  ],
  // Seeker -> rivet dart: a riveted, striped dart.
  seeker: [
    '..........',
    '...kkkkk..',
    '.kkaAaAak.',
    'hhkgggggak',
    '.kkaAaAak.',
    '...kkkkk..',
    '..........',
  ],
  // Sniper -> core drill: a long drill bit on a striped housing.
  sniper: [
    '........kkkk..',
    '.......kaAaak.',
    'kkkkkkkkgggak.',
    'hlhlhlhkgnnggk',
    'kkkkkkkkgggak.',
    '.......kaAaak.',
    '........kkkk..',
  ],
  // Spinner -> saw disc: a toothed saw blade (drawn spinning).
  spinner: [
    '...kkhhkk..',
    '.kkhkhkkhk.',
    'khkhhhhhkk.',
    'kkhhhahgghk',
    'hkhhanaggkk',
    'hhhannnaggh',
    'kkhhanaggkh',
    'khhggagggkk',
    '.kkgggggkhk',
    '.khkkgkhkk.',
    '..kkhhkk...',
  ],
};
for (const [name, rows] of Object.entries(RUST_ART)) ART[name + '_rust'] = rows;
for (const [name, rows] of Object.entries(FROST_ART)) ART[name + '_frost'] = rows;

// Frostring's own enemies (Ice Harvester style).
// Rime Guard, frozen in its ice shell (harmless until it breaks free)...
ART.rimeIced = [
    '...kkkkkkkk...',
    '..kiiiiijjjk..',
    '.kiiimmmmjjjk.',
    'kiiiqqqqqqmjjk',
    'kiiqaAaAaqmjmk',
    'kihhqgnngaqmmk',
    'kihhqgggggaqmk',
    'kijqqqqqqqimmk',
    'kjjmmmmmmimmmk',
    '.kjjjmmmmmmmk.',
    '..kjjjmmmmmk..',
    '...kkkkkkkk...',
];
// ...and once free: a striped gunship with twin guns in front.
ART.rimeGuard = [
    '...kkkkkk...',
    '..kaAaAaAak.',
    '.kkgggggggkk',
    'hhkgnlaangak',
    'hhkgnaalngak',
    '.kkgggggggkk',
    '..kaAaAaAak.',
    '...kkkkkk...',
];
// Cryo Layer: an ore hauler with a frost mine slung in its belly.
ART.cryoLayer = [
    '....kkkkkkkk....',
    '...kaAaAaAaAk...',
    'kkkkgggggggggkk.',
    'kahgnnnnnnnngggk',
    'kkkkgggggggggkk.',
    '....kkkkkkkkk...',
    '.....kjmjk......',
    '.....kmqmk......',
    '......kkk.......',
];
// A frost mine (its amber heart blinks when it's about to burst).
ART.frostMine = [
    '.kkkk.',
    'kjiimk',
    'kiaqmk',
    'kmqamk',
    'kmmqqk',
    '.kkkk.',
];
// Prism: an ice crystal that splits in two when it's hit...
ART.prism = [
    '...kjk...',
    '..kjijk..',
    '.kjiijmk.',
    'kjiiajmqk',
    'jijaaamqm',
    'kjmmamqqk',
    '.kmmmqqk.',
    '..kmqqk..',
    '...kqk...',
];
// ...into two small shards that each fire once.
ART.prismShard = [
    '..k..',
    '.kjk.',
    'kiamk',
    '.kqk.',
    '..k..',
];

// The same pictures at double detail (twice the pixels each way, so each
// grid is exactly twice the size of its normal one). The game draws these
// instead wherever they exist (see detail.js); the normal grids above still
// set every size and hit area.
const HI_ART = {
  // The player's ship, "B: detailed" (owner's pick, v0.20.0): glass canopy
  // with a frame, rivets, a lit fin edge and a glowing engine ring.
  player: [
    '........kkkkk.......................',
    '......kkpPPPpkk.....................',
    '.....kBpPPcPPbpk....................',
    '.....kBppPccbpppk...................',
    '.....kBBpppPbppppk..................',
    '....kkbbbbbbbbbbbbkk................',
    'kkkkkBBBBPPPPPPPPPPPPkkkk...........',
    'koAAkBBBBBpppppppppppppppkkk........',
    'kAlAkBBBBBBpppppppppppaaaallckk.....',
    'kAclkBBBBBBBpppppppppppoooaacccPkk..',
    'kAcckBBBBBBBBBpppppppppppppppccccPkk',
    'kAclkBBpBBBBBpBBBBBpBBBBBbbbbcccckk.',
    'kAlAkbBBBBBBBBBBBBBBBBBBbbbkkkkk....',
    'koAAkbbBBDBBBBBBBBBBbbbkkk..........',
    'kAAAkbpbBBDBBBBBBBbbkk..............',
    'kkkkkkbpbBBDBBBBbbk.................',
    '....kkbbpbBBDBbbk...................',
    '.....kbbbpbBBbbk....................',
    '......kbbbbbbbk.....................',
    '......kDbbbbbDk.....................',
    '.......kDDDDDk......................',
    '........kkkkk.......................',
  ],
  // Level 1 (v0.21.0, approved by the owner from a picture sheet).
  // Pod: rounder, with a panel seam, lit top and a glowing engine.
  drifter: [
    '.......kkkkkk.......',
    '.....kkRssssRkk.....',
    '....kRssrrrrRsRk....',
    '...kRsrrrrrrRrRRk...',
    '..kRsrrrrrrrRrRRkkk.',
    '.kkRsrrrrrrrRrRRRxk.',
    '.kcRrrrrrrrrRrRRRAk.',
    'kccRrrrrrrrrRrRRRlAk',
    'kccRrrrrrrrrRrRRRlAk',
    '.kcRrrrrrrrrRrRRRAk.',
    '.kkRrrrrrrrrRrRRRxk.',
    '..kRRrrrrrrrRrRRkkk.',
    '...kRRrrrrrrRRRxk...',
    '....kRRRrrrRRRxk....',
    '.....kkxxxxxxkk.....',
    '.......kkkkkk.......',
  ],
  // Weaver: ribbed wings, a glowing eye and teeth.
  weaver: [
    '..................kkk.',
    '................kkRRxk',
    '..............kksRRsxk',
    '............kksRRsrRxk',
    '.........kkkssRRsrRRxk',
    '......kkkrssRRsssRRRxk',
    'kkkkkklAssRRsRRRRsRRxk',
    '..kkkklAsRRRRRRRrrRRxk',
    '.kckcxsRRRRRrrrrrrRRxk',
    '.kkckxssrRRRRRRrrrRRxk',
    '..kkkklAssRRrrRRRrRRxk',
    'kkkkkklAsssrRRrrrRRRxk',
    '......kkkxRRrrRRrRRRxk',
    '.........kkkxRrRRrRRxk',
    '............kkxRrRRRxk',
    '..............kkxRRRxk',
    '................kkxRxk',
    '..................kkk.',
  ],
  // Gunship: glass dome, steel frame, twin steel cannons, glowing core.
  gunner: [
    '.........kkkkkkkkkk.........',
    '.......kkGhhhhhhhhGkk.......',
    '......kGhBPPPPPPPBBhGk......',
    '.....kGhBPpppppppPBBhGk.....',
    '....kGhBBPppppppPBBBBhGk....',
    '...kGhBBBBPPPPPPBBBBBBhGk...',
    '.kkkGhBBBBBBBBBBBBBBBBBhGkk.',
    'kkkkkGBBBBBBBBBBBBBBBBBBhGk.',
    'khhhkkRRrrrrssrrrRRBBBBBhGkk',
    'kGGGkkRRrrrsssrrrrRRBBBBhGGk',
    '..kkkkRRrrssyyllrrrRRBBBGGkk',
    '..kkkkRRrrssyyllrrrRRBBBGGkk',
    'khhhkkRRrrrsssrrrrRRBBBBhGGk',
    'kGGGkkRRrrrrssrrrRRBBBBBhGkk',
    'kkkkkGBBBBBBBBBBBBBBBBBBhGk.',
    '.kkkGhBBBBBBBBBBBBBBBBBhGkk.',
    '...kGhBBDBBBBBBBBBBBBBhGk...',
    '....kGhBBDDBBBBBBBBBBhGk....',
    '.....kGhBBDDDBBBBBBBhGk.....',
    '......kGhBBDDDDDBBBhGk......',
    '.......kkGhhhhhhhhGkk.......',
    '.........kkkkkkkkkk.........',
  ],
  // Seeker: a smooth dart with a glowing nose.
  seeker: [
    '.............kkkk...',
    '...........kkRssxk..',
    '.........kkRssrrRxk.',
    '.......kkRssrrrrRxkk',
    '.....kkRssrrrrrrRRxk',
    '..kkkssrrrrrrrrRRRxk',
    'kcyllssrrrrrrrrRRRxk',
    'kcyllsrrrrrrrrrRRRxk',
    '..kkkRRrrrrrrrRRRxxk',
    '.....kkRRrrrrrrRRxxk',
    '.......kkRRrrrrRxxkk',
    '.........kkRRrrRxxk.',
    '...........kkRRxxk..',
    '.............kkkk...',
  ],
  // Sniper: rounded body, long two-tone barrel, red sight lens.
  sniper: [
    '............kkkkkkkkkkkk....',
    '..........kkBBBBBBBPPPPPk...',
    '........kkBBBBBBBBBpppppPk..',
    '.......kBBBBBrrrRBBBBBBBppk.',
    'kkkkkkkkkBBBrsslRBBBBBBBBpk.',
    'khhhhhhhhkkBrsllRBBBBBBBBBpk',
    'cccccclcccckbBrssRBBBBBBBBBk',
    'llllllalllkkbBRrrRBBBBBBBBbk',
    'knnnnnnnnkkbBRRRbBBBBBBBBbk.',
    'kkkkkkkkkbbBBBBBBBBBBBBbbbk.',
    '.......kkbbbbbbbbbbbbbbbbk..',
    '........kbbbbbbbbbbbbbbbbk..',
    '.........kbDDDDDDDDDDDDDk...',
    '..........kkkkkkkkkkkkkk....',
  ],
  // Spinner: a disc with a pale ring, glowing core and four steel spikes.
  spinner: [
    '..........kk..........',
    '..........kk..........',
    '..........GG..........',
    '........kkGGkk........',
    '......kkPPPBBBkk......',
    '.....kbPPPBBBBBbk.....',
    '....kbbPkkPPkkBbbk....',
    '....kPPkPPPpppkBBk....',
    '...kPPkPPRrrRppkBBk...',
    '...kPPkPRrssrRpkBBk...',
    'kkGGPBPPrsyysrppBBggkk',
    'kkGGBBPprsyysrppBDggkk',
    '...kBBkpRrssrRpkDDk...',
    '...kBBkppRrrRppkDDk...',
    '....kBBkppppppkDDk....',
    '....kbbBkkppkkDbbk....',
    '.....kbBBBBBDDDbk.....',
    '......kkBBBDDDkk......',
    '........kkggkk........',
    '..........gg..........',
    '..........kk..........',
    '..........kk..........',
  ],
  // Cargo pod: rounded case, rivets and a framed window (the slot still
  // shows the pickup's light).
  carrier: [
    '....kkkkkkkkkkkkkkkkkk....',
    '..kkPPPPPPPPPPPPPPPPPPkk..',
    '.kppppppppppppppppppppppk.',
    'kppppppppppppppppppppppppk',
    'kBBBBBBBBBBBBBBBBBBBBBBBBk',
    'kBbBBBBBBBBBBBBBBBBBBBBbBk',
    'kBbPBBBknnnnnnnnnnkBBBPbBk',
    'kBbBBBBkkkkkkkkkkkkBBBBbBk',
    'kBbBBBBk..........kBBBBbBk',
    'kBbBBBBk..........kBBBBbBk',
    'kBbBBBBkkkkkkkkkkkkBBBBbBk',
    'kBbPBBBknnnnnnnnnnkBBBPbBk',
    'kBbBBBBBBBBBBBBBBBBBBBBbBk',
    'kbbbbbbbbbbbbbbbbbbbbbbbbk',
    'kbbbbbbbbbbbbbbbbbbbbbbbbk',
    '.kbbbbbbbbbbbbbbbbbbbbbbk.',
    '..kkDDDDDDDDDDDDDDDDDDkk..',
    '....kkkkkkkkkkkkkkkkkk....',
  ],
  // Rust Moon (v0.22.0, approved by the owner from a picture sheet).
  // Sail skiff: a patched sail on a mast, plank deck, a lantern at the bow.
  drifter_rust: [
    '...........kk.......',
    '.........kkcfk......',
    '........kcccfdk.....',
    '.......kccccfddk....',
    '......kcdcccfcddk...',
    '.....kccdcccfccddk..',
    '....kkkkkkkkfkkkkkk.',
    '...kffeffeeffeffeffk',
    '.kAkRrrrrrrrrrrrrrRk',
    'kalkRrrssrrrrrrrrRRk',
    'kllkRrsssrrrreerrRRk',
    'kalkRRrrrrrrrrerrRRk',
    '.kkkxRRRRRRRRRRRRRxk',
    '....kxRRRRRRRRRRRxk.',
    '.....kkxxxxxxxxxkk..',
    '.......kkkkkkkkk....',
  ],
  // Dust bat: ribbed ragged wings, teeth and a glowing eye (a creature).
  weaver_rust: [
    '.............k.....k..',
    '............kdk...kdk.',
    '...........kddfk.kdfdk',
    '..........kdddefkfdddk',
    '.........kdddeeefddddk',
    '........kddeeeeefddek.',
    '........kdeeeeeeeedk..',
    'kk..kkkkseeeeeeeeefk..',
    'kcckllllseeeeeeeeeffk.',
    'kxckllllseeeeeeeeeffk.',
    'kk..kkkkseeeeeeeeefk..',
    '........kfeeeeeeeefk..',
    '........kffeeeeefffk..',
    '.........kfffeeefffffk',
    '..........kfffefkffffk',
    '...........kfffk.kfffk',
    '............kfk...kfk.',
    '.............k.....k..',
  ],
  // Sand galleon: two patched sails, portholes, steel cannons, planked keel.
  gunner_rust: [
    '.............kk.....kk......',
    '............kcfk...kcfk.....',
    '...........kccfdk.kccfdk....',
    '..........kcccfddkcccfddk...',
    '.........kccccfdddcccfdddk..',
    '.........kccdcfddkccdcfddk..',
    '........kkkkkkfkkkkkkkfkkkk.',
    '........kffffffeffffffeffffk',
    'khhhhkkkRrrrrrrrrrrrrrrrrRk.',
    'knnnnkkRrsssrrrrrrrrrrrrRRk.',
    '.kkkkRRrkcckkcckkcckrrrrRRk.',
    '.kkkkRRrkcckkcckkcckrrrrRRk.',
    '.kkkkRRrkcckkcckkcckrrrrRRk.',
    'khhhhkkRrrrrrrrrrrrrrrrrRRk.',
    'knnnnkkRRrrrrrrrrrrrrrrrRRk.',
    '..kkkRRRRRRRRRRRRRRRRRRRRRk.',
    '....kxRRRRRRRRRRRRRRRRRRxk..',
    '.....kfeefeefeefeefeefeek...',
    '.....kffeffeffeffeffeffk....',
    '......kkkkkkkkkkkkkkkkkk....',
    '............................',
    '............................',
  ],
  // Kite glider: canvas wings with spars, a glowing nose.
  seeker_rust: [
    '............kk......',
    '..........kkcfk.....',
    '........kkccfddk....',
    '....kkkkcccfdddrk...',
    '..kkccccccfddddrrk..',
    '.kccccccfdddddrrrk..',
    'kalRRRRRRRRRRRRrrrrk',
    'kaaRRRRRRRRRRRRrrrRk',
    '.kccccccfdddddrrRk..',
    '..kkccccccfddddrRk..',
    '....kkkkcccfdddRk...',
    '........kkccfddk....',
    '..........kkcfk.....',
    '............kk......',
  ],
  // Harpoon gun: a barbed harpoon on a long steel shaft, a small sail.
  sniper_rust: [
    '.....................kk.....',
    '....................kcck....',
    '...................kccfdk...',
    '...................kccfdk...',
    '...................kccfdk...',
    '.................kkcccfdk...',
    '...............kkkkkkfkkkk..',
    'k.k...........kRRRRRRfRrrRk.',
    'kckkhhhhhhhhhhhRrrrrrrrrrRRk',
    'kcckGnnnnnnnnnnRrsssrrrrrRRk',
    'k.k...........kRRsrrrrrRReek',
    '..............kRRRRRRRRRRek.',
    '...............kxRRRRRRRxk..',
    '................kkkkkkkkk...',
  ],
  // Windmill: four framed canvas sails round a hub (it spins).
  spinner_rust: [
    '.......kkkkfk.........',
    '......kccccfk.........',
    '......kccccfk.........',
    '......kccccfk.........',
    '......kccddfk.........',
    '......kddddfk.........',
    '......kccccfk.kkkkkkk.',
    '......kccccfkkccddccck',
    '.......kkffffkccddccck',
    'kkkkkkkkfRRRRfccddccck',
    'fffffffffReeRfccddccck',
    'kcccddccfReeRfffffffff',
    'kcccddccfRRRRfkkkkkkkk',
    'kcccddcckffffkk.......',
    'kcccddcckkfcccck......',
    '.kkkkkkk.kfcccck......',
    '.........kfddddk......',
    '.........kfddddk......',
    '.........kfcccck......',
    '.........kfcccck......',
    '.........kfcccck......',
    '.........kfkkkk.......',
  ],
  // Cliff turret, shut: an armoured dome with a hatch seam on a striped base.
  turretShut: [
    '........kkkkkk........',
    '......kkAAAAookk......',
    '.....kAAllllooook.....',
    '....kAAAAAoooooook....',
    '....kAAAAoooooooxk....',
    '...kAAkkkkkkkkkkxxk...',
    '...kAAAoooooooxxxxk...',
    '...kAAoooooooxxxxxk...',
    'kkkkkkkkkkkkkkkkkkkkkk',
    'kGGGGGGGGGGGGGGGGGGGGk',
    'kgRRggRRggRRggRRggRRgk',
    'kRRggRRggRRggRRggRRggk',
    'knnnnnnnnnnnnnnnnnnnnk',
    'kkkkkkkkkkkkkkkkkkkkkk',
  ],
  // Cliff turret, open: its glowing core and barrel showing.
  turretOpen: [
    '........kkkkkk........',
    '......kkAAAAAAkk......',
    '.....kkkkRrrrrrAk.....',
    'kkkkkkkkkRrsssrook....',
    'cccccccccrsslssook....',
    'lcclcclccrslllsoook...',
    'kkkkkkkkkrsssssoook...',
    '...kkkkkkRrrsrroook...',
    'kkkkkkkkkkkkkkkkkkkkkk',
    'kGGGGGGGGGGGGGGGGGGGGk',
    'kgRRggRRggRRggRRggRRgk',
    'kRRggRRggRRggRRggRRggk',
    'knnnnnnnnnnnnnnnnnnnnk',
    'kkkkkkkkkkkkkkkkkkkkkk',
  ],
  // Dust skimmer: a smooth hull, an amber canopy, a glowing nose.
  skimmer: [
    '.............kkkkkk.....',
    '...........kkaAyAAak....',
    '.......kkkkkaaaAAaaaak..',
    '.....kkoooooaaaaaaaaaak.',
    '..kkkkoooooooaaaaaaaaaak',
    '.kllcoooooooooooooooooRk',
    '.kllcoooooooooooooooooRk',
    '.kllcoooooooooooooooooRk',
    'kyllcooooooooooooooooRRk',
    '.kkkkRRRRRRRRRRRRRRRRRRk',
    '.....kRRxRRxRRxRRxRRkk..',
    '......kkkkkkkkkkkkkkk...',
  ],
  // Mortar crawler: a lit mortar tube on six jointed legs.
  crawler: [
    '...kkk......................',
    '..kGok......................',
    '..kGook.....................',
    '...kGook....................',
    '....kGook...................',
    '.....kGook..................',
    '......kGookkkkkkkkkkkkkkk...',
    '......kRRRRRRRRRRRRRRRRRk...',
    '.....kRrrrrrrrrrrrrrrrrrRk..',
    '.....kRrrssrrrrrrrrrssrrRk..',
    '....kRRrrssrrrrrrrrrssrrRRk.',
    '....kRRRRRRRRRRRRRRRRRRRRRk.',
    '....kxxxxxxxxxxxxxxxxxxxxxk.',
    '....kkkkkkkkkkkkkkkkkkkkkkk.',
    '....kn.kn..kn.....kn..kn.kn.',
    '...kn..kn..kn.....kn..kn..kn',
    '..kn..kn..kn.....kn..kn..kn.',
    '..k...k...k......k...k...k..',
  ],
  // Rust Raider: steel wings, an amber cockpit, a glowing nose gun.
  raider: [
    '.....................kkkk.',
    '...................kkGggk.',
    '.................kkGgggk..',
    '................kGgggggk..',
    '...............kGgggggk...',
    '.............kkRRRrrrrRk..',
    '.....kkkkkkkkRRRrrrrrrRRk.',
    '..kkkgGgRRRRRRsssrraaaaRRk',
    'kcllggggRRRRRRssrrayaaRRRk',
    '.kkkkkkkRRRRRRrrrrrrRRRRk.',
    '.............kkRRRrrrrRk..',
    '...............kgggggnk...',
    '................kgggggnk..',
    '................kgggggnk..',
    '................kgggggnk..',
    '.................kkgggnk..',
    '...................kkgnk..',
    '.....................kkkk.',
  ],
  // The Siege Crawler's mine: eight spikes and a light in the middle.
  mine: [
    '.....kppk.....',
    '..k..kggk..k..',
    '.kpk.kggk.kpk.',
    '..kgkkPPkkgk..',
    '...kPPPBBBk...',
    'kkkkPPBBBBkkkk',
    'pggPPBssBBbggp',
    'pggPBBssBbbggp',
    'kkkkBBBBbbkkkk',
    '...kBBBbbbk...',
    '..kgkkbbkkgk..',
    '.kpk.kggk.kpk.',
    '..k..kggk..k..',
    '.....kppk.....',
  ],
  // The Siege Crawler's drone.
  drone: [
    '...kkkkkkkkk....',
    '..kGAAoooooAAk..',
    '.kgGAooooooooAk.',
    'kllcoooooooooRRk',
    'kllcoooooooooRRk',
    'kllcoooooooooRRk',
    'kyccoooooooooRRk',
    '.kggAooooooooAk.',
    '..kgAAoooooAAk..',
    '...kkkkkkkkk....',
  ],
  lifeIcon: [
    '....kkk.......',
    '...kpPPk......',
    'kkkBppPpkkkk..',
    'kAkBBppppppPkk',
    'klkBBBpppaalck',
    'kckBBBBBBBBcck',
    'kAkbBBBBBbkkk.',
    'kkkbbBBBbk....',
    '...kbbbbk.....',
    '....kkkk......',
  ],
  // Frostring (Ice Harvesters), v0.23.0. Drill pod: an amber hazard-painted barrel with a spiral drill nose
  drifter_frost: [
    '....kkk.kkk.kkk.....',
    '...klllklllklllkkk..',
    '..kaaakaaakaaakaaak.',
    '.kaaakaaakaaakaaakak',
    '.kaakaaakaaakaaakaak',
    '.kAkAAAkAAAkAAAkAAAk',
    '.kGGnGGGGGGGGGGGlaAk',
    'kGnhngghgghgghggaaAk',
    'knhhnggnggnggnggaaAk',
    '.khnnnnnnnnnnnnnaaAk',
    '..kaaakaaakaaakaaak.',
    '.kaaakaaakaaakaaakak',
    '..kAkAAAkAAAkAAAkAk.',
    '...k.kkk.kkk.kkk.k..',
    '....................',
    '....................',
  ],
  // Tunnel grub: banded segments and a round mouth of teeth
  weaver_frost: [
    '......................',
    '......................',
    '.......kkkkkkkk.......',
    '....kkkcecccecckkk....',
    '...keccceccceccceck...',
    '..kdeccdeccdeccdecek..',
    '.ksdeccdeccdeccdeceek.',
    'ksxscccdeccdeccdeceeek',
    'kxxxsccdeccdeccdeceeek',
    'kxxxcccdeccdeccdeceeek',
    'kcxcsccdeccdeccdeceeek',
    '.kcefddefddefddefdeek.',
    '..kefddefddefddefdek..',
    '...kfeeffeeffeeffek...',
    '....kkkffeeffeekkk....',
    '.......kkkkkkkk.......',
    '......................',
    '......................',
  ],
  // Ice cutter: amber cab fore and aft of a grey hull, a saw blade out front
  gunner_frost: [
    '.........kk.kkk.kkk.........',
    '.......kkllklllklllk........',
    '......kaaakaaakaaakak.......',
    '.....kaaakaaakaaakaak.......',
    '.....kaakaaakaaakaaak.......',
    '...kkAAkAAAkAAAkAAAkAkkk....',
    '.kknGnnnnnnnnnnnnnnnnnnnk...',
    'kGGGGGnnnnnnnnnnnnnnnnnnk...',
    'GGGGGGhnGGGGGGGGGGGGGGlaak..',
    'GGGGhhhnggggggggggggggaaAk..',
    'GGGlhhhnggmjnnnnggggggaaAk..',
    'GGhlhhhhggnnnnnnggggggaaAk..',
    'GhhhhhhnggggggggggggggaaAk..',
    'Ghhhhhnnnnnnnnnnnnnnnnaaak..',
    'kkhhnhnnnnnnnnnnnnnnnnnnk...',
    '..khnnnnnnnnnnnnnnnnnnnnk...',
    '...kkaaakaaakaaakaaakkkk....',
    '.....kakaaakaaakaaak........',
    '......kaaakaaakaaakak.......',
    '......kaakaaakaaakaak.......',
    '.......kkAAAkAAAkAAk........',
    '.........kkk.kkk.kk.........',
  ],
  // Rivet dart: an amber dart with a riveted grey spine and a steel needle
  seeker_frost: [
    '....................',
    '....................',
    '.......kk.kkk.kkk...',
    '......kllklllklllk..',
    '.....kaakaaakaaakak.',
    '.kkkkAAkAAAkAAAkAAk.',
    'khGGnGGhGGhGGhGGlaAk',
    'khhhnggnggnggnggaaAk',
    '.kkkkaaakaaakaaakak.',
    '.....kakaaakaaakaak.',
    '....kAkAAAkAAAkAAAk.',
    '.....k.kkk.kkk.kkk..',
    '....................',
    '....................',
  ],
  // Core drill: a long spiral bit on an amber-capped housing with a sight
  sniper_frost: [
    '.................kk.kkk.....',
    '................kllklllkk...',
    '...............kaakaaakaak..',
    '...............kAkAAAkAAAk..',
    '...............kGGGGGGGGGk..',
    '.kkkkkkkkkkkkkkngggggggggkk.',
    'khllGGllGGllGGlnggnalngggGgk',
    'kGAhhAAhhAAhhAAnggnnnngggggk',
    '.kkkkkkkkkkkkkkngggggggggkk.',
    '...............knnnnnnnnnk..',
    '...............kaakaaakaak..',
    '...............kakaaakaaak..',
    '................kAAAkAAAk...',
    '.................kkk.kkk....',
  ],
  // Saw disc: twelve teeth round a striped hub
  spinner_frost: [
    '...........k..........',
    '......kkk.kGk.........',
    '.....kGGGkkGGk.kk.....',
    '......kGGGGGGGkGhk....',
    '...kkkGGGGGGGGhhhk....',
    '..kGGGGGGGGGnhhhhk.k..',
    '..kGGGGGGGGGGnnhhhkhk.',
    '...kGGGGGGGGGhhhhghhk.',
    '..kGGGGGGaakkhhhgghhk.',
    '.kGGGnGGkaakaagggghk..',
    'kGGGGnGGkknnaagggggkk.',
    '.kkGGnGGaannkkggggghhk',
    '..kGGnGGaakaakgggghhk.',
    '.kGGGhhhhkkaaggggghk..',
    '.kGGhhhhhgggggggggk...',
    '.kGkhhhhhggggnngghhk..',
    '..k.khhhggggnggghhhk..',
    '....khhgggggggghkkk...',
    '....khhkhhgghhhk......',
    '.....kk.khhkkhhhk.....',
    '.........khk.kkk......',
    '..........k...........',
  ],
  // Rime Guard, free: twin guns, an amber eye
  rimeGuard: [
    '........kkk.kkk.kkk.....',
    '.......klllklllklllk....',
    '......kaaakaaakaaakak...',
    '.....kAAAkAAAkAAAkAAk...',
    '.kkkkGGGGGGGGGGGGGGGGk..',
    'knGGGggggnnnnnnnnggggkk.',
    'knhhhggggnnnlannnghgglAk',
    '.kkkkggggnnllaannggggaAk',
    'knGGGggggnnaaAAnnggggaAk',
    'knhhhggggnnnaAnnnghggaAk',
    '.kkkkggggnnnnnnnnggggkk.',
    '....knnnnnnnnnnnnnnnnk..',
    '.....kaakaaakaaakaaak...',
    '.....kakaaakaaakaaak....',
    '......kAAAkAAAkAAAk.....',
    '.......kkk.kkk.kkk......',
  ],
  // Rime Guard frozen in its ice shell (the gunship seen through the ice)
  rimeIced: [
    '....kkkkkkkkkkkkkkkkkkkk....',
    '...kjiiiiiiiiiijjjjjjjjjk...',
    '..kjiiiiiiiiiijjjjjjjjjjqk..',
    '.kjiPPiiiiiiijjjjjjjjjijjqk.',
    'kjiiicPPiiqqqjqqqjqqqjjijjqk',
    'kiiiiiiiPPaaakaaakaaaqjjjmmk',
    'kiiiiiiikAPAkAAAkAAAkAqjmmmk',
    'kiiiiiiqoookoookoookooqmmmmk',
    'kiiqqqqjjjjjjjjjjjjjjjjqmmmk',
    'kiqqjjjmmmmqqqqqqqqmmmmqqmmk',
    'kiqqjjjmmmmqqqaAqqqmjmmaoqmk',
    'kiiqqqqmmmmqqaaAAqqmmmmAoqmk',
    'kiqqjjjmmmmqqAAooqqmmmmAoqmk',
    'kjqqjjjmmmmqqqAoqqqmjmmAoqmk',
    'kjjqqqqmmmmqqqqqqqqmmmmqqmmk',
    'kjjjjjqqqqqqqqqqqqqqiqqqmmmk',
    'kjjjjjjqAAkAAAkAAAkAiAqmmmmk',
    'kjjjjjjqAkAAAkAAAkAAAimmmmmk',
    'kjjjjjjjqoookoookoookimmmmmk',
    'kjjjjjjjjqqqmqqqmqqqmmimmmqk',
    '.kqjjjjjmmmmmmmmmmmmmmmmmqk.',
    '..kqjjmmmmmmmmmmmmmmmmmmqk..',
    '...kqmmmmmmmmmmmmmmmmmmqk...',
    '....kkkkkkkkkkkkkkkkkkkk....',
  ],
  // Cryo Layer: an ore hauler with an amber roof, full of ice, a frost mine beneath
  cryoLayer: [
    '.........kk.kkk.kkk.kkk.........',
    '........kllklllklllklllk........',
    '.......kaakaaakaaakaaakak.......',
    '.......kAkAAAkAAAkAAAkAAkk......',
    '.......kGGGGGGGGGGGGGGGGGGk.....',
    '.kkkkkkkggggggggggggggggggkkkkk.',
    'kglahhggnnjnnjnnjnnjnnjngggggGgk',
    'kgaahhggnnmnnnmnnnmnnnmnggggggnk',
    '.kkkkkkkggggggggggggggggggkkkkk.',
    '.......knnnnnnnnnnnnnnnnnnk.....',
    '........kkkkknnnnkkkkkkkkk......',
    '............knjjnk..............',
    '............kjjmmk..............',
    '...........kjlamqqk.............',
    '...........kjmmqqqk.............',
    '............kmqqqk..............',
    '.............kqqk...............',
    '..............kk................',
  ],
  // Frost mine: an ice ball with an amber heart
  frostMine: [
    '....kkkk....',
    '...kiijjk...',
    '..kiijjjjk..',
    '.kicjjjjmmk.',
    'kiijjjjmjmmk',
    'kijjjlammmqk',
    'kjjjjaAmmqqk',
    'kjjjmmmmqqqk',
    '.kjmqmmqqqk.',
    '..kmmmqqqk..',
    '...kmqqqk...',
    '....kkkk....',
  ],
  // Prism: a faceted crystal with an amber core
  prism: [
    '........kk........',
    '.......kijk.......',
    '......kiijjk......',
    '.....kiiijjjk.....',
    '....kiiiijjjjk....',
    '...kiPiiijjjPjk...',
    '..kiiiPiijjPjjjk..',
    '.kiiiiiPlaPjjjjjk.',
    'kiiiiiillaajjjjjjk',
    'kmmmmmmaaAAqqqqqqk',
    '.kmmmmmmaAmqqqqqk.',
    '..kmmmmmmqqmqqqk..',
    '...kmmmmmqqqmqk...',
    '....kmmmmqqqqk....',
    '.....kmmmqqqk.....',
    '......kmmqqk......',
    '.......kmqk.......',
    '........kk........',
  ],
  // Prism shard
  prismShard: [
    '....kk....',
    '...kijk...',
    '..kiijjk..',
    '.kiPijPjk.',
    'kiiilajjjk',
    'kmmmaAqqqk',
    '.kmmmqmqk.',
    '..kmmqqk..',
    '...kmqk...',
    '....kk....',
  ],
};

function build(rows, colorOverride) {
  const w = Math.max(...rows.map((r) => r.length));
  const h = rows.length;
  const cv = document.createElement('canvas');
  cv.width = w;
  cv.height = h;
  const ctx = cv.getContext('2d');
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < rows[y].length; x++) {
      const ch = rows[y][x];
      if (ch === '.') continue;
      ctx.fillStyle = colorOverride || KEY[ch] || '#ff00ff';
      ctx.fillRect(x, y, 1, 1);
    }
  }
  return cv;
}

export const SPRITES = {};
for (const [name, rows] of Object.entries(ART)) {
  SPRITES[name] = build(rows);
  SPRITES[name + 'Flash'] = build(rows, PAL.cream);
  const hi = HI_ART[name];
  if (hi) {
    SPRITES[name].hi = build(hi);
    SPRITES[name + 'Flash'].hi = build(hi, PAL.cream);
  }
}
// For the tests: which pictures have a double-detail version.
export const HI_NAMES = Object.keys(HI_ART);
